# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Projects/ERN24004/Projects/PYNQ/04_PMOD_AD1/ad1/ad1.srcs/sources_1/bd/ad1/ip/ad1_rst_ps7_0_50M_0/ad1_rst_ps7_0_50M_0.xci
# IP: The module: 'ad1_rst_ps7_0_50M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Projects/ERN24004/Projects/PYNQ/04_PMOD_AD1/ad1/ad1.gen/sources_1/bd/ad1/ip/ad1_rst_ps7_0_50M_0/ad1_rst_ps7_0_50M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'ad1_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Projects/ERN24004/Projects/PYNQ/04_PMOD_AD1/ad1/ad1.gen/sources_1/bd/ad1/ip/ad1_rst_ps7_0_50M_0/ad1_rst_ps7_0_50M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'ad1_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Projects/ERN24004/Projects/PYNQ/04_PMOD_AD1/ad1/ad1.gen/sources_1/bd/ad1/ip/ad1_rst_ps7_0_50M_0/ad1_rst_ps7_0_50M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ad1_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Projects/ERN24004/Projects/PYNQ/04_PMOD_AD1/ad1/ad1.srcs/sources_1/bd/ad1/ip/ad1_rst_ps7_0_50M_0/ad1_rst_ps7_0_50M_0.xci
# IP: The module: 'ad1_rst_ps7_0_50M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Projects/ERN24004/Projects/PYNQ/04_PMOD_AD1/ad1/ad1.gen/sources_1/bd/ad1/ip/ad1_rst_ps7_0_50M_0/ad1_rst_ps7_0_50M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'ad1_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Projects/ERN24004/Projects/PYNQ/04_PMOD_AD1/ad1/ad1.gen/sources_1/bd/ad1/ip/ad1_rst_ps7_0_50M_0/ad1_rst_ps7_0_50M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'ad1_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Projects/ERN24004/Projects/PYNQ/04_PMOD_AD1/ad1/ad1.gen/sources_1/bd/ad1/ip/ad1_rst_ps7_0_50M_0/ad1_rst_ps7_0_50M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ad1_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
