# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/coraz7.xdc

# Block Designs: bd/ad1/ad1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ad1 || ORIG_REF_NAME==ad1} -quiet] -quiet

# IP: bd/ad1/ip/ad1_processing_system7_0_0/ad1_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ad1_processing_system7_0_0 || ORIG_REF_NAME==ad1_processing_system7_0_0} -quiet] -quiet

# IP: bd/ad1/ip/ad1_PmodAD1_0_0/ad1_PmodAD1_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ad1_PmodAD1_0_0 || ORIG_REF_NAME==ad1_PmodAD1_0_0} -quiet] -quiet

# IP: bd/ad1/ip/ad1_auto_pc_0/ad1_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ad1_auto_pc_0 || ORIG_REF_NAME==ad1_auto_pc_0} -quiet] -quiet

# IP: bd/ad1/ip/ad1_ps7_0_axi_periph_0/ad1_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ad1_ps7_0_axi_periph_0 || ORIG_REF_NAME==ad1_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/ad1/ip/ad1_rst_ps7_0_50M_0/ad1_rst_ps7_0_50M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ad1_rst_ps7_0_50M_0 || ORIG_REF_NAME==ad1_rst_ps7_0_50M_0} -quiet] -quiet

# XDC: c:/Projects/ERN24004/Projects/PYNQ/04_PMOD_AD1/ad1/ad1.gen/sources_1/bd/ad1/ad1_ooc.xdc
