# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/coraz7.xdc

# Block Designs: bd/pmod_ad1/pmod_ad1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pmod_ad1 || ORIG_REF_NAME==pmod_ad1} -quiet] -quiet

# IP: bd/pmod_ad1/ip/pmod_ad1_processing_system7_0_0/pmod_ad1_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pmod_ad1_processing_system7_0_0 || ORIG_REF_NAME==pmod_ad1_processing_system7_0_0} -quiet] -quiet

# IP: bd/pmod_ad1/ip/pmod_ad1_PmodAD1_0_0/pmod_ad1_PmodAD1_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pmod_ad1_PmodAD1_0_0 || ORIG_REF_NAME==pmod_ad1_PmodAD1_0_0} -quiet] -quiet

# IP: bd/pmod_ad1/ip/pmod_ad1_auto_pc_0/pmod_ad1_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pmod_ad1_auto_pc_0 || ORIG_REF_NAME==pmod_ad1_auto_pc_0} -quiet] -quiet

# IP: bd/pmod_ad1/ip/pmod_ad1_ps7_0_axi_periph_0/pmod_ad1_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pmod_ad1_ps7_0_axi_periph_0 || ORIG_REF_NAME==pmod_ad1_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/pmod_ad1/ip/pmod_ad1_rst_ps7_0_50M_0/pmod_ad1_rst_ps7_0_50M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pmod_ad1_rst_ps7_0_50M_0 || ORIG_REF_NAME==pmod_ad1_rst_ps7_0_50M_0} -quiet] -quiet

# XDC: c:/Projects/ERN24004/Projects/PMOD_AD1/PMOD_AD1.gen/sources_1/bd/pmod_ad1/pmod_ad1_ooc.xdc
